version: '3.8'

services:
  postgres:
    environment:
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_DB: ${SQL_DATABASE}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
    networks:
      - orders-hub-network-test
    env_file:
      - ./.env.test
    ports:
      - "5433:5432"

  redis:
    ports:
      - "6380:6379"

  web:
    environment:
      DJANGO_SETTINGS_MODULE: OrdersHub.settings
    command:
      - bash
      - -c
      - |
        while !</dev/tcp/postgres/5432; do sleep 1; done;
        while !</dev/tcp/redis/6379; do sleep 1; done;
        python manage.py test --noinput  # Run the tests without any input
    volumes:
      - .:/orders_hub
    networks:
      - orders-hub-network-test
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.env.test
    ports:
      - "8001:8000"

volumes:
  local_postgres_data_test: {}
  redis_data_test: {}

networks:
  orders-hub-network-test:
    name: orders-hub-network-test
